game/urls.py
from django.urls import path, include
from . import views

from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='game'
urlpatterns = [
	#Home
	path('', views.home, name="home"),

	#Lobby
	path('lobbies/', views.lobbies, name="lobbies"),
	path('createlobby/', views.lobbyForm, name="createlobby"),
	path('lobbies/<str:lobby_name>/', views.inLobby, name='lobby'),
	path('add_user_lobby/<lobby_name>/', views.addUser, name='add_user'),
	path('delete_lobby/<lobby_name>/', views.cancelLobby, name='cancel-lobby'),

	#Game
	path('game/<lobby_name>/', views.inGame, name="game"),

	#These are the urls for the registering and logging in for normal user
	path('register/', views.register, name="register"),
	path('login/', views.loginPage, name="login"),
	path('logout/', views.userLogout, name="logout"),

	#GameMaster Login
	path('login_gamemaster/', views.loginGamemaster, name="login_gamemaster"),

	#Password Reset
	path('password_reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"), name="password_reset"),
	path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_sent.html"), name="password_reset_sent"),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_form.html"), name="password_reset_confirm"),
	path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_done.html"), name="password_reset_complete"),
]

#For the Images
urlpatterns += staticfiles_urlpatterns()

groupsoftware/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),

]

game/models.py
from django.db import models
from django.contrib.auth.models import User, Group
import uuid

class Lobby(models.Model):
	lobby_name = models.CharField(max_length=200, default='Test', unique=True)
	users = models.ManyToManyField(User)
	#gameMaster = models.OneToOneField(User, on_delete=models.CASCADE)
	gameState = models.IntegerField(default=0)

	def __str__(self):
		return self.lobby_name
	def _users(self):
		return self.users.all()
	def _players(self):
		return self.player_set.all()
	def _is_occupied(self):
		return self.users.count() <= 11
	def _gameState(self):
		return self.gameState


class Player(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
	isImposter = models.BooleanField(default=False)
	isAlive = models.BooleanField(default=False)
	gpsLongitude = models.FloatField(default=0)
	gpsLatitude = models.FloatField(default=0)
	lobby = models.ForeignKey(Lobby, on_delete=models.CASCADE, default=None)
	color = models.CharField(max_length=15, default="white")


	def __str__(self):
		return self.user.username
	def _user(self):
		return self.user
	def _isImposter(self):
		return self.isImposter
	def _isAlive(self):
		return self.isAlive
	def _gpsLongitude(self):
		return self.gpsLongitude
	def _gpsLatitude(self):
		return self.gpsLatitude
	def _color(self):
		return self.color

	def _taskList(self):
		return self.task_set.all()


class Task(models.Model):

	player = models.ForeignKey(Player, on_delete=models.CASCADE, default=None, blank=True, null=True)
	taskName =  models.CharField(max_length=200, default='Task')
	gpsLongitude = models.FloatField(default=0)
	gpsLatitude = models.FloatField(default=0)
	taskNumber = models.IntegerField(default=0)
	isDone = models.BooleanField(default=False)

	def __str__(self):
		return self.taskName
	def _player(self):
		return self.player
	def _gpsLongitude(self):
		return self.gpsLongitude
	def _gpsLatitude(self):
		return self.gpsLatitude
	def _taskNumber(self):
		return self.taskNumber
	def _isDone(self):
		return self.isDone

game/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

#Forms
class CreateUserForm(UserCreationForm):
	email = forms.EmailField(required=True, label='email',widget=forms.TextInput(attrs={'placeholder':'Email...'})) #Telling you that email is required
	username = forms.CharField(label='username',widget=forms.TextInput(attrs={'placeholder':'Username...'}))
	password1 = forms.CharField(label='password1',widget=forms.PasswordInput(attrs={'placeholder':'Password...'})) 
	password2 = forms.CharField(label='password2',widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password...'})) 

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2'] #This is the fields being used on the form

	#Function for saving the form
	def save(self, commit=True):
		user = super(CreateUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class LobbyForm(forms.ModelForm):
	class Meta:
		model = Lobby
		fields = ['lobby_name']

game/views.py
#What you need to render the html and files
from turtle import color
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.forms import inlineformset_factory

#For the login and registeration system
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group

from django.template import loader
from django.http import Http404
from django.http import JsonResponse

import json
import sys
import random



#GeoDjango
#from django.views import generic
#from django.contrib.gis.geos import fromstr
#from django.contrib.gis.db.models.functions import Distance
#from .models import Tasks

#Using the other functions from the other files
from .forms import *
from .utils import *
from .models import *

#Registration & Login
def register(request):
	#If you are logged in already it will send you to the home
	if request.user.is_authenticated:
		return redirect('game:home')
	else:
		if request.method == 'POST':
			form = CreateUserForm(request.POST) #Creates the form using the forms.py
			if form.is_valid():
				user = form.save() #Saves the form
				messages.info(request, "Registration Successful")
				return redirect('game:login') #Redirects you to login after registration is successful

			messages.error(request, "Unsuccessful Registration. Invalid information") #This is when it doesn't have the requirements it asks
		form = CreateUserForm() #For making the form
	context = {'form':form}
	return render(request, 'users/register.html', context)

def loginPage(request):
	#If you are logged in already it will send you to the home
	if request.user.is_authenticated:
		return('game:home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username') #Asks for username
			password = request.POST.get('password') #Asks for password
			#This authenicates and checks the username and password
			user = authenticate(request, username=username, password=password)
			#If the user is incorrect it won't run this
			if is_gamemaster(user) == False:
				if user is not None:
					login(request, user)
					return redirect('game:home') #Redirects to home
				else:
					messages.info(request, 'Username or Password is incorrect')
			else:
				messages.info(request, 'This account is a Gamemaster, Go to the Gamemaster Login')

	context = {}
	return render(request, 'users/login.html', context)

def loginGamemaster(request):
	#If you are logged in already it will send you to the home
	if request.user.is_authenticated:
		return('game:home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username') #Asks for username
			password = request.POST.get('password') #Asks for password
			#This authenicates and checks the username and password
			user = authenticate(request, username=username, password=password)
			#If the user is incorrect it won't run this
			if is_gamemaster(user) == True:
				if user is not None:
					login(request, user)
					return redirect('game:home') #Redirects to home
				else:
					messages.info(request, 'Username or Password is incorrect')
			else:
				messages.info(request, 'Your Account is not a Gamemaster')

	context = {}
	return render(request, 'users/login_gamemaster.html', context)

def userLogout(request):
	logout(request) #Simple logout request sends you back to login
	return redirect('game:login')

@login_required(login_url='game:login') #This is used to tell the webapp that you can't access the homepage without logging in
def home(request):
	return render(request, "users/home.html")

#Lobby
@login_required(login_url='game:login')
def lobbies(request):
	Player.objects.filter(user = request.user).delete
	listlobbies = Lobby.objects.all().filter(gameState = 0)
	context = {'listlobbies': listlobbies}
	return render(request, "game/lobbies.html", context)

@login_required(login_url='game:login')
def inLobby(request, lobby_name):
	thislobby = get_object_or_404(Lobby, pk=lobby_name)
	if request.method=='POST':
		thislobby.gameState=1
		thislobby.save()
		users = thislobby._users()
		colors = ['black', 'blue', 'red', 'orange', 'light_green', 'yellow', 'pink', 'purple', 'light_blue', 'dark_green']
		#players created
		print("The length of users " + str(len(users)))
		for i in range(len(users)):
			player = Player(user = users[i], lobby = thislobby, color = colors[i])
			player.save()
		#decide imposters
		players = Player.objects.all().filter(lobby = thislobby)
		print("THe players" + str(players))
		ran1 = -1
		ran2 = -1
		if len(players) >=7:
			numberOfImposters = 2
			ran1 = random.randint(0,len(players)-1)
			ran2 = random.randint(0,len(players)-1)

		else:
			numberOfImposters = 1
			ran1 = random.randint(0,len(players)-1)
		crewmates = []

		for i in range(0, len(players)):
			player = players[i]
			if i == ran1:
				player.isImposter = True
				player.save()
			else:
				player.isAlive = True
				player.save()
				crewmates.append(player)

		jsonFile = open("game/taskList.txt")
		tasksList = json.load(jsonFile)
		gameTasks = []
		#distribute tasks
		for x in tasksList["tasks"]:
			task = Task(taskName = x["name"], gpsLongitude = x["longitude"], gpsLatitude = x["latitude"], taskNumber =x["number"])
			task.save()
			gameTasks.append(task)
		jsonFile.close()
		noOfTasks = len(gameTasks)-1
		for i in crewmates:
			for j in range(4):
				num = random.randint(0,noOfTasks)
				print(num)
				task = gameTasks[num]
				task.player = i
				task.save()
				gameTasks.remove(task)
				noOfTasks = noOfTasks -1

		url = '/game/' + lobby_name
		return redirect(url)
	else:
		username = request.user
		if thislobby._is_occupied() and thislobby.gameState==0:
			thislobby.users.add(username)
			thislobby.save()
			print(str(thislobby.users))
			return render(request, 'game/lobby.html', {'lobby': thislobby, 'users':thislobby._users})
		else:
			return redirect('game:lobbies')

@login_required(login_url='game:login')
def addUser(request, lobby_name):
	lobby = Lobby.objects.get(pk=lobby_name)
	username = request.user
	print("username" + username)
	if lobby.is_occupied():
		lobby.users.add(username)
		lobby.save()
		return redirect('game:lobby')
	else:
		return redirect('game:lobbies')


@login_required(login_url='game:login')
def cancelLobby(request, lobby_name):
	lobby = Lobby.objects.get(pk=lobby_name)
	lobby.delete()
	return redirect('game:lobbies')

@login_required (login_url='game:login')
def lobbyForm(request):
	form = LobbyForm()
	if request.method == 'POST':
		form = LobbyForm(request.POST)
		if form.is_valid():
			form.save()
			redirect('game:lobbies')
	return render(request,"game/createLobby.html",{'form':form})


#The Game
@login_required(login_url='game:login')
def inGame(request, lobby_name):
	thisLobby = Lobby.objects.get(pk=lobby_name)
	is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
	if is_ajax == True:
		if request.GET.get('longitude') != None:

			location = [request.GET.get('longitude'), request.GET.get('latitude')]
			thisPlayer = Player.objects.get(user = request.user)
			thisPlayer.gpsLongitude = location[0]
			thisPlayer.gpsLatitude = location[1]
			thisPlayer.save()
			otherPlayers = Player.objects.all().filter(lobby = thisLobby).exclude(user = request.user)
			otherPlayerData = []
			for i in range(len(otherPlayers)):
				playerData = []
				anotherPlayer = otherPlayers[i]
				playerData.append(anotherPlayer.gpsLongitude)
				playerData.append(anotherPlayer.gpsLatitude)
				playerData.append(anotherPlayer.color)
				otherPlayerData.append(playerData)
			#wincondition check
			tasksAllFinished = True
			crewmatesAllDead = True
			crewmates = Player.objects.all().filter(lobby = thisLobby).filter(isImposter=False)
			for i in crewmates:
				tasks = Task.objects.all().filter(player = i)
				for j in tasks:
					if j.isDone == False:
						tasksAllFinished = 'false'
				if i.isAlive == True:
					crewmatesAllDead = 'false'
			#winconditioncheck end

			return JsonResponse({'otherPlayerData': otherPlayerData, 'tasksAllFinished':tasksAllFinished, 'crewmatesAllDead': crewmatesAllDead})
		elif request.GET.get('color') != None:
			#wincondition check
			#colorP = request.GET.get('color')
			print("lobby: "+ str(lobby_name) + "color "+str(request.GET.get('color')) )
			player = Player.objects.get(lobby = lobby_name, color=request.GET.get('color'))
			player.isAlive = False
			player.color = 'white'
			player.save()
			crewmatesAllDead = 'true'
			crewmates = Player.objects.all().filter(lobby = thisLobby).filter(isImposter=False)
			for i in crewmates:
				if i.isAlive == True:
					crewmatesAllDead = 'false'
			#winconditioncheck end
			return JsonResponse({'crewmatesAllDead':crewmatesAllDead})
		else:
			taskNum = request.GET.get('taskNumber')
			thisPlayer = Player.objects.get(user = request.user)
			thisTask = Task.objects.get(player = thisPlayer, taskNumber=taskNum)
			thisTask.isDone =True
			thisTask.save()
			tasksAllFinished = True
			crewmates = Player.objects.all().filter(lobby = thisLobby).filter(isImposter=False)
			for i in crewmates:
				tasks = Task.objects.all().filter(player = i)
				for j in tasks:
					if j.isDone == False:
						tasksAllFinished = False
			return JsonResponse({'tasksAllFinished':tasksAllFinished})

	taskLocation = []
	names = []
	locations=[]
	player = Player.objects.get(user = request.user)
	tasks = Task.objects.all().filter(player = player)
	#print("tasks " + str(tasks))
	for i in tasks:
		taskNum = i.taskNumber
		taskLon = i.gpsLongitude
		taskLat =i.gpsLatitude

game/templates/game/createlobby.html
{% extends "users/base.html" %}
{% load static %}
{% load game_extras %}
<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


        <title>Create Lobby</title>
</head>
{% block content %}   
<body class="text-center">
<div class="container2">
<div class="title2">IMPOSTERS</div>
  <div class="subtitle2">CREATE LOBBY</div>
<div class = "form">
<form method="POST">
        {% csrf_token %}
        <div class="lobby">
        {{ form.lobby_name }}
      </div>
<button class="lobby-btn" type="submit" value="Createlobby">Create Lobby</button><br>
<center><a href="/lobbies">Go back to lobbies</a></center>
</form>
</div>
</div>
</div>
</div>
{% endblock %}
</body>
</html>


game/templates/game/game1.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style type="text/css">
		*,
	*:before,
	*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
.popup{
    background-color: #ffffff;
    width: 420px;
    padding: 30px 40px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
    border-radius: 8px;
    display: none;
    font-family: "Poppins",sans-serif;
    text-align: center;
}
.popup button{
    display: block;
    margin:  0 0 20px auto;
    background-color: transparent;
    font-size: 30px;
    color: #ffffff;
    background: #03549a;
    border-radius: 100%;
    width: 40px;
    height: 40px;
    border: none;
    outline: none;
    cursor: pointer;
}
.popup h2{
   margin-top: -20px;
}
.popup p{
    font-size: 14px;
    text-align: justify;
    margin: 20px 0;
    line-height: 25px;
}
	</style>
	<title></title>
</head>
<body>
	<h1>Game</h1>
	<div class="popup">
		<button id="close">&times;</button>
		<h2>Your Role</h2>
	<p>The Rules: Killers are suppose to kill the Innocents while the Innocents try to do all the tasks. If Killers kill everyone, then they win. However, if the Innocents finish the tasks first, they will win. Tasks can be done even if you are dead. Good luck</p>
	</div>
	{% if request.user|has_group:"Killer" %}
	<h3>Killer</h3>
	{% endif %}
	{% if request.user|has_group:"Innocent" %}
	<h3>Innocent</h3>
	{% endif %}
	{% if request.user|has_group:"Gamemaster" %}
	<h3>GameMaster</h3>
	{% endif %}
    <img src="{% static "images/map.png" %}" alt="Map" width=50% height=50%/>
    {% if request.user|has_group:"Killer" %}
    <!-- Player List here-->
    <button>Kill</button>
    {% endif %}
    {% if request.user|has_group:"Innocent" %}
    <!-- Task List here-->
    <button>Do Task</button>
    {% endif %}
    {% if request.user|has_group:"Innocent" %}
    <button>End Game</button>
    {% endif %}
     <script type="text/javascript">
window.addEventListener("load", function(){
    setTimeout(
        function open(event){
            document.querySelector(".popup").style.display = "block";
        },
        2000
    )
});


document.querySelector("#close").addEventListener("click", function(){
    document.querySelector(".popup").style.display = "none";
});
    </script>
</body>
</html>

game/templates/game/lobbies.html
{% extends "users/base.html" %}

{% load game_extras %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lobbies</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body overflow="scroll">

{% block content %}
<h1 style="color: #FFFFFF"><center>Lobbies</center></h1>
<hr style="color: #404040">
<h3 style="color: #B3B3B3">Currently Logged in as: {{user.username|default:'Guest'}}</h3>
{% if request.user|has_group:"Gamemaster" %}
<p style="color: #B3B3B3">You are the role of Gamemaster, you can create lobbies, delete, and start games</p>
{% endif %}
<hr style="color: #404040">
<br>

<!--List of Lobbies-->
<div class="container-fluid">
<div class="row">
{% for lobby in listlobbies %}
<div class="col-auto mb-3">
<div class="card" style="width: 18rem; background-color: #404040;">
	<div class="card-body">
		<h5 class="card-title" style="color: #FFFFFF">{{ lobby.lobby_name }}</h5>
    <a href="{% url 'game:lobby' lobby.id %}" class="btn btn-primary">Go To Lobby</a>

	</div>
</div>
</div>
{% endfor %}
</div>
</div>
<hr style="color: #404040">
<!--Button to create lobby-->
{% if request.user|has_group:"Gamemaster" %}

<a href="/createlobby"><button>Create Lobby</button></a>

{% endif %}
{% endblock %}

</body>
</html>

game/templates/game/lobby.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	{% load game_extras %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<style type="text/css">
		.header{
			background-color: #4e4e4e;
			padding-top: 2%;
			padding-bottom: 0.5%;
		}

	</style>
	
	<title>Lobby</title>
</head>
<body style="background-color: #222222">
<center><div class="header"><h1 style="color: white">{{ lobby.lobby_name }}</h1></center></div></center>
<hr style="color: #404040">
{% block content %}

<!--Player list will be here-->
<h3><u style="color: #FFFFFF"><p style="color: #FFFFFF; margin-left: 2.5%;">Player List</p></h3></u>
<ul style="list-style-type: none; margin-left: 2.5%;">
{% for user in users %}
    <li style="color: #B3B3B3">{{ user.username }}</li>
{% endfor %}
</ul>
{% if request.user|not_group:"Gamemaster" %}
<center><a href="/lobbies"><button>Leave Lobby</button></a></center>
{% endif %}
{% if request.user|has_group:"Gamemaster" %}
<hr style="color: #404040">
<div class="row">
<form action="" method="post">
		{% csrf_token %}
    <button name="Start Game" value="True">Start Game</button>
</form>


<a href="{% url 'game:cancel-lobby' lobby.id %}"><button>Cancel Game</button></a>
</div>
{% endif %}
{% endblock %}

    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ lobby.lobby_name|json_script:"lobby-name" }}
	{{ user.username|json_script:"user-name" }}
    <script>
        const lobbyName = JSON.parse(document.getElementById('lobby-name').textContent);
		const username = JSON.parse(document.getElementById('user-name').textContent);
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/lobbies/'
            + lobbyName
            + '/'
        );

        chatSocket.onmessage = function(e) {
    
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (JSON.parse(document.getElementById('user-name').textContent) +': ' + data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };
        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>